### ISSUE TITLE
Playtime on the player info page does not appear correctly if the user has a day or more of playtime

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/SS14.Admin#12]
If the player has a day or more of playtime, the player info page will cut that playtime off.

**Comment by PJB3005** [comment]
Is that's why I thought play time tracking is broken.

Am I actually this stupid?

**Comment by PJB3005** [comment]
For what it's worth, I've set up a DB trigger to make sure that the play time table never rolls back. So it's only possible for time to fail to count, rather than people actually going backwards.

**Comment by PJB3005** [comment]
Ok so that was true *when I wrote that*. I checked the table again and there are a few (rare) cases of losses of upwards to 50 minutes.

**Comment by Biglulux** [comment]
I have a rather severe issue with this. I have all roles unlocked, including all heads and captain. I asked to be whitelisted for MRP, and Nairodian said he only saw my playtime as six hours. I know I've played about 90 hours according to my steam time, and it was all on lizard. Somehow the DB lost all my playtime.

**Comment by PJB3005** [comment]
Fixed by e1c80e8d220a12e9b5cd0fc73d3c9791127b3806
