### ISSUE TITLE
Role bans "Active" list shows all bans

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/SS14.Admin#33]
Searching for active role bans includes expired and lifted bans. I only tested this when using a search string, so I'm not sure if it also happens in the full list.

**Comment by Geekyhobo** [comment]
I was able to reproduce this, ill look into it

**Comment by Geekyhobo** [comment]
pretty sure it has to do with how the "search" is handled ie guid hwid, it writes over the show filter, or just ignores it think i have a fix

**Comment by PJB3005** [comment]
I'm like 99% sure this is a bug in EF Core or Npgsql.

**Comment by PJB3005** [comment]
It's fixed by updating EF Core / Npgsql to .NET 8.
