### ISSUE TITLE
Role bans cant be unbanned.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/SS14.Admin#62]
Think its related to #60 on unbanning a role ban get this error:
![image](https://github.com/space-wizards/SS14.Admin/assets/47093363/369f8c5a-794e-4bcf-b140-6da98921afd1)
Also redirects to the ban page not the roleban page.
Does not actually unban checked in game in banlist for user and ban still exists.

@Geekyhobo If you can shed any light on it 🙉

**Comment by Geekyhobo** [comment]
fuck, i fix
