### ISSUE TITLE
Admin just 404s if you're not authorized

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/SS14.Admin#65]
Ideally I'd just get redirected to login but if I try to hit bans or players it just gives me a 404 and I have to remember where to go manually.

Specifically https://ss14-admin.spacestation14.com/admin/Bans gets redirected to which is invalid if you try to go to the old URL.

**Comment by PJB3005** [comment]
Are you trying to access it through `central.spacestation14.io/admin` still? I think the redirect is broken.

**Comment by PJB3005** [comment]
This was a config issue, fixed on our servers. Nginx sucks.
